import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Heap Bufferflow</title>
        <meta name="keywords" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainnav}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Blog</li>
          <li>Contact</li>
        </ul>
      </nav>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            A place to find your coding solutions
          </p>

        </div>



        <div className='blogs'>
          <h2>Popular Blogs</h2>
          <div className='blogItem'>
            <h3>How to learn Javascript in 2023?</h3>
            <p>Javascript is the language used to design logic for the web</p>
          </div>
          <div className='blogItem'>
            <h3>How to learn Javascript in 2023?</h3>
            <p>Javascript is the language used to design logic for the web</p>
          </div>
          <div className='blogItem'>
            <h3>How to learn Javascript in 2023?</h3>
            <p>Javascript is the language used to design logic for the web</p>
          </div>
        </div>
      </main>
    </>
  )
}
